definitions:
  controllers.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.Score:
    properties:
      country:
        type: string
      score:
        type: number
      state:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /get_rank:
    get:
      description: Get rank of a user
      parameters:
      - description: User name
        in: query
        name: user_name
        required: true
        type: string
      - description: 'Scope: state, country, or globally'
        in: query
        name: scope
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User rank
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Get rank
  /list_top_n:
    get:
      description: List top N ranks
      parameters:
      - description: Number of ranks to list
        in: query
        name: "n"
        required: true
        type: integer
      - description: 'Scope: state, country, or globally'
        in: query
        name: scope
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Top N scores
          schema:
            items:
              $ref: '#/definitions/models.Score'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: List top N
  /submit:
    post:
      consumes:
      - application/json
      description: Submit score to the system
      parameters:
      - description: Score object
        in: body
        name: score
        required: true
        schema:
          $ref: '#/definitions/models.Score'
      produces:
      - application/json
      responses:
        "200":
          description: Score submitted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Submit score
swagger: "2.0"
